# Generated by Django 5.0.1 on 2025-11-28 09:02

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Campaign',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('geo', models.CharField(help_text='Geo code страны (например, AU, MX, RO)', max_length=10)),
                ('offer_id', models.IntegerField(help_text='ID оффера Keitaro')),
                ('domain', models.CharField(blank=True, max_length=255)),
                ('group', models.CharField(blank=True, max_length=255)),
                ('source', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Кампания',
                'verbose_name_plural': 'Кампании',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Flow',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('keitaro_id', models.IntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=255)),
                ('flow_type', models.CharField(choices=[('country_filter', 'Фильтр по стране (редирект на Google)'), ('offer_redirect', 'Редирект на оффер')], max_length=20)),
                ('country', models.CharField(blank=True, help_text='Код страны для фильтра', max_length=10)),
                ('redirect_url', models.URLField(blank=True, help_text='URL для редиректа (Google или оффер)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='flows', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Поток',
                'verbose_name_plural': 'Потоки',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='CampaignOffer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('offer_id', models.IntegerField(help_text='ID оффера Keitaro')),
                ('offer_name', models.CharField(blank=True, max_length=255)),
                ('weight', models.IntegerField(default=1, help_text='Вес оффера для ротации')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('campaign', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campaign_offers', to='campaigns.campaign')),
            ],
            options={
                'verbose_name': 'Оффер кампании',
                'verbose_name_plural': 'Офферы кампании',
                'ordering': ['-weight', 'id'],
                'unique_together': {('campaign', 'offer_id')},
            },
        ),
    ]
