# Generated by Django 5.0.1 on 2025-11-28 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaigns', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaignoffer',
            name='flow',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='offers', to='campaigns.flow'),
        ),
        migrations.AddField(
            model_name='campaignoffer',
            name='status',
            field=models.CharField(choices=[('active', 'Активен'), ('removed', 'Удален')], default='active', max_length=20),
        ),
        migrations.AddField(
            model_name='campaignoffer',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AddField(
            model_name='campaignoffer',
            name='weight_pinned',
            field=models.BooleanField(default=False, help_text='Закреплен ли вес оффера'),
        ),
        migrations.AddField(
            model_name='flow',
            name='has_changes',
            field=models.BooleanField(default=False, help_text='Есть ли неопубликованные изменения'),
        ),
        migrations.AddField(
            model_name='flow',
            name='is_published',
            field=models.BooleanField(default=True, help_text='Опубликован ли поток в Keitaro'),
        ),
        migrations.AddField(
            model_name='flow',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
